### ISSUE TITLE
support `yield`ing Promises in middlewares

### ISSUE THREAD

**Issue by andrewdhazlett** [zipscene/yaar#1]
Feature request: wrap middlewares in `co` or bluebird `Promise.coroutine` to support `yield`ing promises inline

**Comment by rosshadden** [comment]
Since `Promise` is a first class citizen in node, supporting those are the only thing we are interested in.  Thus we're not going to add support for this.

`yield` isn't really meant for such things anyway.  I don't know about bluebird, but TJ made co because we didn't have `async`/`wait` support yet, and thus did what he could with generators.  Support for these lies behind a flag now, and has perfect interoperability with native promises.  I have been using them in personal projects for some time now, and am very happy with it.
